apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi  # Make sure this matches your PVC
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /mnt/data  # Adjust this path as needed (ensure it exists on your nodes)


